name: Build and Deploy MedBotAssist WebAPI (.NET)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore MedBotAssist.WebApi.sln

      - name: Build solution
        run: dotnet build MedBotAssist.WebApi.sln --configuration Release --no-restore

      - name: Publish WebAPI project
        run: dotnet publish MedBotAssist.WebApi/MedBotAssist.WebApi.csproj --configuration Release --output ./publish

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: medbotassist
          slot-name: production
          package: ./publish
