name: Deploy Python Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'BackEnd/MedBotAssist.BotOpenIA/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: BackEnd/MedBotAssist.BotOpenIA
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure startup.sh exists and is correct
        run: |
          cd BackEnd/MedBotAssist.BotOpenIA
          if [ ! -f startup.sh ]; then
            echo "Creating startup.sh"
            cat > startup.sh << 'EOF'
          #!/bin/bash
          pip install --upgrade pip
          pip install -r requirements.txt
          python server.py
          EOF
          fi
          chmod +x startup.sh
          ls -la startup.sh

      - name: Zip backend folder for deployment
        run: |
          cd BackEnd/MedBotAssist.BotOpenIA
          zip -r ../../medbotopenia.zip .

      - name: Check for startup.sh in ZIP
        run: unzip -l medbotopenia.zip | grep -i startup || echo "startup.sh NOT FOUND in ZIP"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: medBotAssistAI
          slot-name: production
          publish-profile: ${{ secrets.AZURE_MEDBOTASSISTOPENIA_PUBLISH_PROFILE }}
          package: medbotopenia.zip