name: Deploy Python Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'BackEnd/MedBotAssist.BotOpenIA/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: BackEnd/MedBotAssist.BotOpenIA
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure startup.sh is executable
        run: chmod +x BackEnd/MedBotAssist.BotOpenIA/startup.sh
      
      - name: Zip backend folder for deployment
        run: |
          cd BackEnd/MedBotAssist.BotOpenIA
          zip -r ../../medbotopenia.zip ./*
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: medBotAssistAI
          slot-name: production
          publish-profile: ${{ secrets.AZURE_MEDBOTASSISTOPENIA_PUBLISH_PROFILE }}
          package: medbotopenia.zip
